"""initial_schema_v0_1

Revision ID: 88bccecba56e
Revises: 
Create Date: 2026-06-05 05:42:52.643908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bccecba56e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('mrn_hash', sa.String(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_mrn_hash'), 'audit_log', ['mrn_hash'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mrn', sa.String(), nullable=False),
    sa.Column('disease_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_plan_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('fhir_patient_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mrn')
    )
    op.create_table('kb_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewer_1', sa.String(), nullable=True),
    sa.Column('reviewer_1_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_2', sa.String(), nullable=True),
    sa.Column('reviewer_2_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected','withdrawn')", name='ck_kbrev_status'),
    sa.CheckConstraint('reviewer_1 IS NULL OR reviewer_2 IS NULL OR reviewer_1 != reviewer_2', name='ck_two_distinct_reviewers'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_reviews_entity_id'), 'kb_reviews', ['entity_id'], unique=False)
    op.create_index(op.f('ix_kb_reviews_status'), 'kb_reviews', ['status'], unique=False)
    op.create_table('mtd_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('scheduled','in_progress','completed')", name='ck_mtd_session_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('mrn', sa.String(), nullable=False),
    sa.Column('masked_name', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('dob_year', sa.Integer(), nullable=True),
    sa.Column('disease_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('primary_doctor_id', sa.String(), nullable=True),
    sa.Column('his_patient_id', sa.String(), nullable=True),
    sa.Column('his_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.CheckConstraint("sex IN ('M','F','O')", name='ck_patient_sex'),
    sa.CheckConstraint("status IN ('active','discharged','deceased')", name='ck_patient_status'),
    sa.PrimaryKeyConstraint('mrn')
    )
    op.create_index(op.f('ix_patients_his_patient_id'), 'patients', ['his_patient_id'], unique=False)
    op.create_table('plans',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('mrn', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('supersedes', sa.String(), nullable=True),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.Column('revision_trigger', sa.Text(), nullable=True),
    sa.Column('selected_track_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','superseded','rejected')", name='ck_plan_status'),
    sa.ForeignKeyConstraint(['superseded_by'], ['plans.plan_id'], ),
    sa.ForeignKeyConstraint(['supersedes'], ['plans.plan_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_plans_mrn'), 'plans', ['mrn'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.Text(), nullable=False),
    sa.Column('auth_key', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_push_endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('google_sub', sa.String(), nullable=False),
    sa.Column('google_email', sa.String(), nullable=False),
    sa.Column('google_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('pending','tumor_board_hcp','clinic_hcp','kb_admin','auditor')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('annotation_type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("annotation_type IN ('approve','comment','flag','reject','select_track')", name='ck_annotation_type'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_plan_id'), 'annotations', ['plan_id'], unique=False)
    op.create_table('care_team_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_mrn', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('member_role', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("member_role IN ('primary_hcp','care_coordinator','consultant')", name='ck_care_team_member_role'),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.mrn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_mrn', 'user_id', name='uq_care_team_patient_user')
    )
    op.create_index(op.f('ix_care_team_members_patient_mrn'), 'care_team_members', ['patient_mrn'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_mrn', sa.String(), nullable=False),
    sa.Column('from_user_id', sa.String(), nullable=False),
    sa.Column('to_user_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('open','replied','closed')", name='ck_consult_status'),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.mrn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_patient_mrn'), 'consultations', ['patient_mrn'], unique=False)
    op.create_table('drug_requisitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('mrn', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('requisition_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('draft','submitted','approved','rejected')", name='ck_dreq_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_requisitions_plan_id'), 'drug_requisitions', ['plan_id'], unique=False)
    op.create_table('his_sync_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_mrn', sa.String(), nullable=True),
    sa.Column('raw_mrn', sa.String(), nullable=False),
    sa.Column('his_event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('sync_source', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("his_event_type IN ('appointment','medication','lab_result','imaging','discharge')", name='ck_his_event_type'),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.mrn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_his_sync_events_patient_mrn'), 'his_sync_events', ['patient_mrn'], unique=False)
    op.create_index(op.f('ix_his_sync_events_raw_mrn'), 'his_sync_events', ['raw_mrn'], unique=False)
    op.create_index(op.f('ix_his_sync_events_received_at'), 'his_sync_events', ['received_at'], unique=False)
    op.create_table('mtd_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mtd_session_id', sa.String(), nullable=False),
    sa.Column('patient_mrn', sa.String(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('conclusion_text', sa.Text(), nullable=True),
    sa.Column('conclusion_by', sa.String(), nullable=True),
    sa.Column('conclusion_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending','discussed','deferred')", name='ck_mtd_case_status'),
    sa.ForeignKeyConstraint(['mtd_session_id'], ['mtd_sessions.id'], ),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.mrn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mtd_session_id', 'patient_mrn', name='uq_mtd_case_session_patient')
    )
    op.create_index(op.f('ix_mtd_cases_mtd_session_id'), 'mtd_cases', ['mtd_session_id'], unique=False)
    op.create_index(op.f('ix_mtd_cases_patient_mrn'), 'mtd_cases', ['patient_mrn'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_mrn', sa.String(), nullable=False),
    sa.Column('reminder_type', sa.String(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("reminder_type IN ('drug_reapplication','pending_lab','imaging_due','followup_appt','brca_result','his_sync_stale','custom')", name='ck_reminder_type'),
    sa.CheckConstraint("status IN ('active','acknowledged','expired')", name='ck_reminder_status'),
    sa.CheckConstraint("urgency IN ('low','normal','high','critical')", name='ck_reminder_urgency'),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.mrn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_due_date'), 'reminders', ['due_date'], unique=False)
    op.create_index(op.f('ix_reminders_patient_mrn'), 'reminders', ['patient_mrn'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_mrn', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("event_type IN ('his_sync','doctor_note','coordinator_note','alert','consultation_reply','mtd_conclusion','onco_query_initiated','drug_reminder')", name='ck_tl_event_type'),
    sa.CheckConstraint("source IN ('his_sync','manual','system_rule')", name='ck_tl_source'),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.mrn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_event_time'), 'timeline_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_timeline_events_patient_mrn'), 'timeline_events', ['patient_mrn'], unique=False)
    op.create_table('consultation_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('consultation_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_messages_consultation_id'), 'consultation_messages', ['consultation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_messages_consultation_id'), table_name='consultation_messages')
    op.drop_table('consultation_messages')
    op.drop_index(op.f('ix_timeline_events_patient_mrn'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_time'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_reminders_patient_mrn'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_due_date'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_mtd_cases_patient_mrn'), table_name='mtd_cases')
    op.drop_index(op.f('ix_mtd_cases_mtd_session_id'), table_name='mtd_cases')
    op.drop_table('mtd_cases')
    op.drop_index(op.f('ix_his_sync_events_received_at'), table_name='his_sync_events')
    op.drop_index(op.f('ix_his_sync_events_raw_mrn'), table_name='his_sync_events')
    op.drop_index(op.f('ix_his_sync_events_patient_mrn'), table_name='his_sync_events')
    op.drop_table('his_sync_events')
    op.drop_index(op.f('ix_drug_requisitions_plan_id'), table_name='drug_requisitions')
    op.drop_table('drug_requisitions')
    op.drop_index(op.f('ix_consultations_patient_mrn'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_care_team_members_patient_mrn'), table_name='care_team_members')
    op.drop_table('care_team_members')
    op.drop_index(op.f('ix_annotations_plan_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_table('users')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_plans_mrn'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_patients_his_patient_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('mtd_sessions')
    op.drop_index(op.f('ix_kb_reviews_status'), table_name='kb_reviews')
    op.drop_index(op.f('ix_kb_reviews_entity_id'), table_name='kb_reviews')
    op.drop_table('kb_reviews')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_mrn_hash'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
